---
- name: Example Playbook
  hosts: localhost
  connection: local

  tasks:
    - name: Print a message
      debug:
        msg: "Hello, Ansible on localhost!"

# ansible-playbook -i "localhost," playbook.yml
