name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        

      - name: Terraform Init (with backend)
        run: terraform init -reconfigure

      - name: Verify Terraform backend & State
        run: terraform state list

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
