name: Destroy EC2

on: workflow_dispatch

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Find State File
        run: |
          echo "Looking for state files..."
          find . -name "*.tfstate"
          find . -name ".terraform" -type d

      - name: Terraform Init (with explicit backend)
        run: terraform init -reconfigure

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -state=terraform.tfstate \
            -state-out=terraform.tfstate \
            -backup=terraform.tfstate.backup

      - name: Verify Resources Destroyed
        run: aws ec2 describe-instances --filters "Name=tag:CreatedBy,Values=Terraform"
