  ansible:
    needs: runterraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Purge all configs
        run: |
          rm -rf ~/.ansible/
          rm -rf ~/.ssh/
          mkdir -p ~/.ssh/

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ needs.runterraform.outputs.public_ip }} >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa

      - name: Debug setup
        run: |
          ls -la ~/.ssh/
          ssh-keygen -l -f ~/.ssh/id_rsa

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: python -m pip install --upgrade pip && pip install ansible

      - name: Create Inventory
        run: |
          echo '[ec2_instance]' > inventory.ini
          echo '${{ needs.runterraform.outputs.public_ip }} ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa ansible_user=ec2-user' >> inventory.ini

      - name: Run Ansible Playbook
        run: |
          ANSIBLE_SSH_ARGS="-vvv -o IdentitiesOnly=yes -o IdentityFile=/home/runner/.ssh/id_rsa" \
          ansible-playbook -i inventory.ini playbook.yml \
            --private-key=/home/runner/.ssh/id_rsa \
            -vvvv
